apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops-tools
  labels:
    app: jenkins
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-service
#   namespace: jenkins-ns
#   annotations:
#     networking.gke.io/load-balancer-type: "External"
# spec:
#   type: NodePort
#   externalTrafficPolicy: Cluster
#   selector:
#     app: jenkins
#   ports:
#   - name: tcp-port
#     protocol: TCP
#     port: 8080
#     targetPort: 8080